version: '3'

services:
  redis:
    image: redis:latest
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "4000:80"
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=db
      - POSTGRES_HOST_AUTH_METHOD=trust
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
     - DB_USER=postgres
     - DB_PASSWORD=postgres_password
     - DB_HOST=postgres
     - DB_PORT=5432
     - DB_NAME=db
     - REDIS_HOST=redis
     - REDIS_PORT=6379
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules