version: '3'

services:
  redis:
    image: redis:latest
  postgre:
    image: postgres:latest
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
     - DB_USER=postgres
     - DB_PASSWORD=postgres_password
     - DB_HOST=postgres
     - DB_PORT=5432
     - DB_NAME=postgres
     - REDIS_HOST=redis
     - REDIS_PORT=6379
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"